name: Create VPC-RDS AWS Connectivity

on:
  push:
    branches:
      - main

jobs:
  aws-connectivity:
    runs-on: ubuntu-latest 

    steps:
      # Paso 1: Checkout del código
      - name: Checkout code
        uses: actions/checkout@v3

      # Paso 2: Instalar AWS CLI
      - name: Install AWS CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y awscli

      # Paso 3: Instalar Terraform
      - name: Install Terraform
        run: |
          # Descargar la clave GPG de HashiCorp
          wget -O - https://apt.releases.hashicorp.com/gpg | sudo gpg --dearmor -o /usr/share/keyrings/hashicorp-archive-keyring.gpg
          
          # Agregar el repositorio de HashiCorp
          echo "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/hashicorp.list
          
          # Actualizar apt e instalar Terraform
          sudo apt update && sudo apt install -y terraform

      # Paso 4: Configurar las credenciales de AWS
      - name: Configure AWS credentials
        run: |
          aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws configure set aws_session_token ${{ secrets.AWS_SESSION_TOKEN }}
          aws configure set region us-east-1

      # Paso 5: Ejecutar el comando aws sts get-caller-identity
      - name: Get AWS Caller Identity
        run: aws sts get-caller-identity
        
      # Paso 6: Ejecutar terraform init
      - name: Initialize Terraform
        run: |
          cd infra
          terraform init

      # Paso 7: Verificar si los recursos ya existen antes de aplicar
      - name: Check if resources already exist
        run: |
          cd infra
          terraform plan -out=plan.out

          # Buscar si la salida de terraform plan contiene recursos que ya existen
          if grep -q "already exists" plan.out; then
            echo "Los recursos ya existen. No es necesario crear nuevos."
            exit 0  # Salir sin aplicar cambios
          else
            echo "No existen recursos previos. Continuando con terraform apply."
          fi

      # Paso 8: Ejecutar terraform apply solo si no existen los recursos
      - name: Apply Terraform configuration if resources don't exist
        run: |
          cd infra
          terraform apply -auto-approve
