name: Generate Infrastructure Diagram

on:
  push:
    branches:
      - main

jobs:
  generate-diagram:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y graphviz
          python -m pip install --upgrade pip
          pip install diagrams python-hcl2

      - name: Crear archivo Python temporal con el código
        run: |
          echo "
          import os
          import hcl2
          from diagrams import Diagram, Cluster, Node
          from diagrams.aws.compute import EC2
          from diagrams.aws.database import RDS
          from diagrams.aws.network import VPC, InternetGateway, Subnet
          from diagrams.aws.security import SecurityGroup
          
          # Crear un diagrama
          with Diagram('AWS Infrastructure', show=False, filename='diagram'):
              # VPC
              vpc = VPC('VPC (Virtual Private Cloud)\nCIDR: 10.0.0.0/16')
              
              # Subredes
              with Cluster('Public Subnet\nCIDR: 10.0.1.0/24'):
                  public_subnet = EC2('EC2 Instance\nPublic Access')
              
              with Cluster('Private Subnet\nCIDR: 10.0.2.0/24'):
                  private_subnet = RDS('RDS Instance\nMySQL 5.7')
              
              # Internet Gateway
              igw = InternetGateway('Internet Gateway\nmy_igw')
              
              # Security Group
              rds_sg = SecurityGroup('RDS Security Group\nPort: 3306 (MySQL)')
          
              # Conexiones
              vpc >> igw >> public_subnet
              vpc >> private_subnet
              private_subnet >> rds_sg >> private_subnet

          " > script.py

      - name: Generar el diagrama
        run: |
          python script.py

      - name: Verificar existencia de diagram.png
        run: |
          if [ -f diagram.png ]; then
            echo "Diagrama generado correctamente"
          else
            echo "El archivo diagram.png no se generó. Abortando..."
            exit 1
          fi

      - name: Eliminar archivo temporal script.py
        run: |
          rm script.py

      - name: Commit and Push Diagram
        run: |
          git config --local user.name "JesusHuallpa"
          git config --local user.email "jh2021071085@virtual.upt.pe"
          
          if [ -f "diagram.png" ]; then
              git checkout diagramaTF || git checkout -b diagramaTF
              git add diagram.png
              git commit -m "Actualizar diagrama de infraestructura [skip ci]" || echo "No hay cambios para commit"
              git push origin diagramaTF --force
          else
              echo "Error: diagram.png no se generó."
              exit 1
          fi
