name: Terraform Infrastructure with Diagram Generation

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      # Check out the code from the repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # Set up Terraform
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: '1.5.0'

      # Initialize Terraform
      - name: Terraform Init
        run: terraform init

      # Generate Terraform Plan
      - name: Terraform Plan
        run: terraform plan

      # Apply Terraform (auto-approve)
      - name: Terraform Apply
        run: terraform apply -auto-approve

      # Install dependencies for HCL2 (optional if needed for your diagram generation)
      - name: Install HCL2 (if necessary)
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-pip
          pip3 install hcl2

      # Generate the infrastructure diagram (replace with your diagram generation command)
      - name: Generate Infrastructure Diagram
        run: |
          # Example: generate the diagram with a command (replace with actual tool and command)
          python3 generate_infrastructure_diagram.py

      # Upload generated diagram as artifact (optional)
      - name: Upload Infrastructure Diagram
        uses: actions/upload-artifact@v2
        with:
          name: infrastructure-diagram
          path: path/to/generated/diagram.png

      # Clean up after apply (optional)
      - name: Clean up Terraform
        run: terraform destroy -auto-approve
