
name: infracost

on:
  workflow_dispatch:
    branches:
      - main
jobs:
  aws-connectivity:
    runs-on: ubuntu-latest

    steps: 
      # Paso 1: Checkout del código
      - name: Checkout code
        uses: actions/checkout@v3

      # Paso 2: Instalar AWS CLI
      - name: Install AWS CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y awscli

      # Paso 3: Configurar las credenciales de AWS
      - name: Configure AWS credentials
        run: |
          aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws configure set region us-east-1

      # Paso 4: Verificar las credenciales con AWS STS
      - name: Get AWS Caller Identity
        run: aws sts get-caller-identity

      # Paso 5: Obtener costos con AWS Cost Explorer (para Lambda, S3 y Glue)
      - name: Get AWS Cost Data for Lambda, S3, and Glue
        id: cost_data
        run: |
          # Ejecutar la consulta a AWS Cost Explorer para obtener costos de Lambda, S3 y Glue
          COSTS=$(aws ce get-cost-and-usage \
            --time-period Start=$(date +%Y-%m-01),End=$(date +%Y-%m-28) \
            --granularity MONTHLY \
            --metrics "BlendedCost" \
            --group-by Type=DIMENSION,Key=SERVICE \
            --filter '{"Dimensions":{"Key":"SERVICE","Values":["AWS Lambda","Amazon S3","AWS Glue"]}}')

          echo "AWS Cost Data for Lambda, S3, and Glue: $COSTS"
          echo "COSTS=$COSTS" >> $GITHUB_ENV

      # Paso 6: Instalar Infracost
      - name: Install Infracost
        run: |
          curl -fsSL https://raw.githubusercontent.com/infracost/infracost/master/scripts/install.sh | sh
          infracost configure set api_key ${{ secrets.INFRACOST_API_KEY }}
          infracost configure set currency USD

      - name: Generate Infracost Breakdown
        working-directory: ./infra
        run: |
          # Generar el desglose mensual con Infracost
          infracost breakdown --path=tfplan.json --format json --out-file infracost.json
          
          # Verificar que el costo mensual esté presente
          infracost output --path infracost.json --format table > infracost_monthly.txt
          
          # Extraer los costos específicos de los servicios de AWS Cost Explorer y agregarlos al archivo
          LAMBDA_COST=$(echo ${{ env.COSTS }} | jq '.ResultsByTime[0].Groups[] | select(.Keys[0] == "AWS Lambda") | .Metrics.BlendedCost.Amount')
          S3_COST=$(echo ${{ env.COSTS }} | jq '.ResultsByTime[0].Groups[] | select(.Keys[0] == "Amazon S3") | .Metrics.BlendedCost.Amount')
          GLUE_COST=$(echo ${{ env.COSTS }} | jq '.ResultsByTime[0].Groups[] | select(.Keys[0] == "AWS Glue") | .Metrics.BlendedCost.Amount')

          echo "Costo mensual de AWS Lambda: $LAMBDA_COST" >> infracost_monthly.txt
          echo "Costo mensual de Amazon S3: $S3_COST" >> infracost_monthly.txt
          echo "Costo mensual de AWS Glue: $GLUE_COST" >> infracost_monthly.txt

      # Paso 13: Mostrar el informe de costos mensuales
      - name: Display Infracost Reports
        working-directory: ./infra
        run: |
          echo "COSTOS MENSUALES:"
          cat infracost_monthly.txt

      # Paso 14: Subir informes de costos como artefactos
      - name: Upload Infracost Reports
        uses: actions/upload-artifact@v3
        with:
          name: infracost-reports
          path: |
            ./infra/infracost.json
            ./infra/infracost_monthly.txt
