name: infracost

on:
  workflow_dispatch:
    branches:
      - main

jobs:
  aws-connectivity:
    runs-on: ubuntu-latest

    steps: 
      # Paso 1: Checkout del código
      - name: Checkout Code
        uses: actions/checkout@v3

      # Paso 2: Instalar AWS CLI
      - name: Install AWS CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y awscli

      # Paso 3: Instalar Terraform
      - name: Install Terraform
        run: |
          # Agregar repositorio oficial de HashiCorp
          curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo tee /usr/share/keyrings/hashicorp-archive-keyring.gpg
          echo "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/hashicorp.list
          sudo apt-get update
          sudo apt-get install -y terraform

      # Paso 4: Configurar las credenciales de AWS
      - name: Configure AWS Credentials
        run: |
          aws configure set aws_access_key_id "${{ secrets.AWS_ACCESS_KEY_ID }}"
          aws configure set aws_secret_access_key "${{ secrets.AWS_SECRET_ACCESS_KEY }}"
          aws configure set region "us-east-1"

      # Paso 5: Verificar las credenciales
      - name: Verify AWS Connectivity
        run: aws sts get-caller-identity

      # Paso 6: Inicializar Terraform
      - name: Initialize Terraform
        working-directory: infra
        run: terraform init

      # Paso 7: Validar la configuración de Terraform
      - name: Validate Terraform Configuration
        working-directory: infra
        run: terraform validate

      # Paso 8: Generar el plan de Terraform
      - name: Terraform Plan
        working-directory: infra
        run: |
          terraform plan -out=tfplan
          terraform show -json tfplan > tfplan.json

      # Paso 9: Instalar y configurar Infracost
      - name: Install and Configure Infracost
        run: |
          curl -fsSL https://raw.githubusercontent.com/infracost/infracost/master/scripts/install.sh | sh
          infracost configure set api_key "${{ secrets.INFRACOST_API_KEY }}"
          infracost configure set currency USD

      # Paso 10: Generar el desglose de costos
      - name: Generate Infracost Breakdown
        working-directory: infra
        run: |
          infracost breakdown --path=tfplan.json --format json --out-file infracost.json
          infracost output --path infracost.json --format table > infracost_monthly.txt
          infracost output --path infracost.json --format json | jq '.projects[0].breakdown.totalMonthlyCost * 12' > infracost_annual.txt
      
      # Paso 11: Mostrar informes de costos
      - name: Display Infracost Reports
        working-directory: infra
        run: |
          echo "COSTOS MENSUALES:"
          cat infracost_monthly.txt
          echo "COSTO ANUAL ESTIMADO:"
          cat infracost_annual.txt

      # Paso 12: Subir los informes como artefactos
      - name: Upload Infracost Reports
        uses: actions/upload-artifact@v3
        with:
          name: infracost-reports
          path: |
            infra/infracost.json
            infra/infracost_monthly.txt
            infra/infracost_annual.txt

      # Paso 13: Aplicar la configuración de Terraform (opcional)
      #- name: Apply Terraform Configuration
      #  working-directory: infra
      #  run: terraform apply -auto-approve

      # Paso 14: Limpiar credenciales de AWS
      - name: Clean Up AWS Credentials
        run: |
          unset AWS_ACCESS_KEY_ID
          unset AWS_SECRET_ACCESS_KEY
          unset AWS_SESSION_TOKEN
