name: AWS Cost Report with Infracost

on:
  workflow_dispatch: # Esto permite que el flujo se ejecute manualmente desde la UI de GitHub

jobs:
  aws-connectivity:
    runs-on: ubuntu-latest

    steps:
      # Paso 1: Checkout del código
      - name: Checkout code
        uses: actions/checkout@v3

      # Paso 2: Instalar AWS CLI
      - name: Install AWS CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y awscli

      # Paso 3: Configurar las credenciales de AWS
      - name: Configure AWS credentials
        run: |
          aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws configure set region us-east-1

      # Paso 4: Obtener costos de AWS Cost Explorer
      - name: Get AWS Cost Data for Lambda, S3, and Glue
        id: cost_data
        run: |
          # Formateo la fecha de inicio y fin
          START_DATE=$(date +%Y-%m-01)
          END_DATE=$(date +%Y-%m-28)  # O puedes usar `date +%Y-%m-%d` para el día actual
          
          # Llamo a AWS Cost Explorer para obtener los costos de los servicios
          COSTS=$(aws ce get-cost-and-usage \
            --time-period Start=$START_DATE,End=$END_DATE \
            --granularity MONTHLY \
            --metrics "BlendedCost" \
            --group-by Type=DIMENSION,Key=SERVICE \
            --filter '{"Dimensions":{"Key":"SERVICE","Values":["AWS Lambda","Amazon S3","AWS Glue"]}}' | jq -c '.')

          # Debug: Mostrar la salida de los costos obtenidos
          echo "AWS Cost Data for Lambda, S3, and Glue: $COSTS"

          # Establecer la variable de entorno para los costos
          echo "COSTS=$COSTS" >> $GITHUB_ENV
