name: Execute SQL Script on RDS

on:
  push:
    branches:
      - main

jobs:
  execute-sql-script:
    runs-on: ubuntu-latest

    steps:
      # Paso 1: Instalar AWS CLI
      - name: Install AWS CLI
        run: |
          curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
          unzip awscliv2.zip
          sudo ./aws/install

      # Paso 2: Verificar si la instancia de RDS existe
      - name: Check if RDS instance exists
        run: |
          INSTANCE_EXISTS=$(aws rds describe-db-instances --db-instance-identifier mydb-instance --query "DBInstances[0].DBInstanceIdentifier" --output text)
          
          if [ "$INSTANCE_EXISTS" != "mydb-instance" ]; then
            echo "RDS instance does not exist. Skipping SQL execution."
            exit 0
          else
            echo "RDS instance exists. Proceeding to execute SQL script."
          fi

      # Paso 3: Obtener el endpoint de la instancia de RDS y esperar a que esté disponible
      - name: Wait for RDS to be available and get endpoint
        run: |
          DB_ENDPOINT=$(aws rds describe-db-instances --db-instance-identifier mydb-instance --query "DBInstances[0].Endpoint.Address" --output text)
          
          # Esperar a que MySQL esté disponible
          echo "Waiting for RDS instance to be available..."
          until mysqladmin --host=$DB_ENDPOINT --user=admin --password=$MYSQL_PASSWORD ping --silent; do
            echo "Waiting for MySQL service to be available..."
            sleep 30
          done
          
          echo "RDS instance is available."

      # Paso 4: Ejecutar el script SQL
      - name: Execute SQL script
        run: |
          echo "Executing SQL script..."
          mysql --host=$DB_ENDPOINT --user=admin --password=$MYSQL_PASSWORD mydatabase < artefactos/datos.sql
          echo "SQL script executed successfully."
          
    env:
      MYSQL_PASSWORD: ${{ secrets.MYSQL_PASSWORD }}
