name: Create Release

on:
  push:
    tags:
      - 'v*.*.*' # Actúa cuando se empuja un tag que sigue el formato semántico (ej., v1.0.0).

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Create GitHub Release
      id: create_release
      uses: actions/create-release@v1
      with:
        tag_name: ${{ github.ref_name }}
        release_name: Release ${{ github.ref_name }}
        draft: false
        prerelease: false
        body: |
          **Changelog:**
          - Detalla aquí los cambios realizados.
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Upload Release Assets
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./build/artifact.zip # Cambia al archivo que desees subir.
        asset_name: artifact.zip
        asset_content_type: application/zip
