name: terravision
on:
  push:
    branches:
      - main
jobs:
  aws-connectivity:
    runs-on: ubuntu-latest
    steps:
      # Paso 1: Checkout del código
      - name: Checkout code
        uses: actions/checkout@v3
      # Paso 2: Instalar AWS CLI
      - name: Install AWS CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y awscli
      # Paso 3: Instalar Terraform
      - name: Install Terraform
        run: |
          # Descargar la clave GPG de HashiCorp
          wget -O - https://apt.releases.hashicorp.com/gpg | sudo gpg --dearmor -o /usr/share/keyrings/hashicorp-archive-keyring.gpg
          
          # Agregar el repositorio de HashiCorp
          echo "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/hashicorp.list
          
          # Actualizar apt e instalar Terraform
          sudo apt update && sudo apt install -y terraform
      # Paso 4: Configurar las credenciales de AWS
      - name: Configure AWS credentials
        run: |
          aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws configure set region us-east-1
      # Paso 5: Verificar las credenciales con AWS STS
      - name: Get AWS Caller Identity
        run: aws sts get-caller-identity
      # Paso 6: Inicializar Terraform
      - name: Initialize Terraform
        run: |
          cd infra
          terraform init
      # Paso 7: Aplicar Terraform
      - name: Apply Terraform configuration
        run: |
          cd infra
          terraform apply -auto-approve || (echo "El recurso ya existe. Continuando con la ejecución." && exit 0)
      # Paso 8: Instalar Terravision
      - name: Install Terravision
        run: |
          pip install terravision
      # Paso 9: Generar el diagrama con Terravision
      - name: Generate Infrastructure Diagram
        run: |
          cd infra
          terravision generate \
            --output-format png \
            --output-file diagram.png
      # Paso 10: Subir el diagrama como artefacto
      - name: Upload Diagram Artifact
        uses: actions/upload-artifact@v3
        with:
          name: aws-infrastructure-diagram
          path: infra/diagram.png
