name: Generate Infrastructure Diagram

on:
  push:
    branches:
      - main

jobs:
  generate-diagram:
    runs-on: ubuntu-latest

    steps:
      # Paso 1: Checkout del código
      - name: Checkout Code
        uses: actions/checkout@v3

      # Paso 2: Instalar Python y Terravision
      - name: Install Python and Terravision
        run: |
          sudo apt update
          sudo apt install -y python3 python3-pip
          pip install terravision

      # Paso 3: Instalar Terraform
      - name: Install Terraform
        run: |
          wget -O - https://apt.releases.hashicorp.com/gpg | sudo gpg --dearmor -o /usr/share/keyrings/hashicorp-archive-keyring.gpg
          echo "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/hashicorp.list
          sudo apt update && sudo apt install -y terraform

      # Paso 4: Inicializar y aplicar Terraform
      - name: Terraform Init and Apply
        run: |
          cd infra
          terraform init
          terraform plan
          terraform apply -auto-approve

      # Paso 5: Generar el diagrama de infraestructura
      - name: Generate Infrastructure Diagram
        run: |
          cd infra
          terravision render -o ../diagrama_infraestructura.png

      # Paso 6: Subir el diagrama como artefacto
      - name: Upload Diagram
        uses: actions/upload-artifact@v3
        with:
          name: diagrama_infraestructura
          path: diagrama_infraestructura.png
