name: Create RDS Instance in AWS

on:
  push:
    branches:
      - main

jobs:
  aws-connectivity:
    runs-on: ubuntu-latest

    steps:
      # Paso 1: Checkout del código
      - name: Checkout code
        uses: actions/checkout@v3

      # Paso 2: Instalar AWS CLI
      - name: Install AWS CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y awscli

      # Paso 3: Configurar las credenciales de AWS
      - name: Configure AWS credentials
        run: |
          aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws configure set aws_session_token ${{ secrets.AWS_SESSION_TOKEN }}
          aws configure set region us-east-1

      # Paso 4: Ejecutar el comando aws sts get-caller-identity
      - name: Get AWS Caller Identity
        run: aws sts get-caller-identity

      # Paso 5: Crear DB Subnet Group
      - name: Create DB Subnet Group
        run: |
          aws rds create-db-subnet-group \
            --db-subnet-group-name my-db-subnet-group \
            --db-subnet-group-description "My DB Subnet Group" \
            --subnet-ids subnet-xxxxxxxx subnet-yyyyyyyy

      # Paso 6: Crear la base de datos RDS
      - name: Create RDS Instance
        run: |
          aws rds create-db-instance \
            --db-instance-identifier mydb-instance \
            --db-instance-class db.t2.micro \
            --engine mysql \
            --allocated-storage 20 \
            --storage-type gp2 \
            --vpc-security-group-ids sg-08db0d68f1b78a11e \  # Reemplaza con tu ID de SG
            --db-subnet-group-name my-db-subnet-group \
            --master-username admin \
            --master-user-password SimplePassword123! \
            --db-name mydatabase \
            --publicly-accessible \
            --no-multi-az \
            --backup-retention-period 7
