name: Test AWS Connectivity

on:
  push:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      # Paso 1: Checkout del código
      - name: Checkout code
        uses: actions/checkout@v3

      # Paso 2: Configurar las credenciales de AWS desde los secretos de GitHub
      - name: Set up AWS credentials for Terraform
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}
        run: |
          echo "AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}" >> $GITHUB_ENV
          echo "AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}" >> $GITHUB_ENV
          echo "AWS_SESSION_TOKEN=${{ secrets.AWS_SESSION_TOKEN }}" >> $GITHUB_ENV

      # Paso 3: Instalar Terraform
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1

      # Paso 4: Inicializar Terraform
      - name: Terraform Init
        run: terraform init

      # Paso 5: Ejecutar Terraform Apply para aplicar los cambios
      - name: Terraform Apply
        run: terraform apply -auto-approve
