name: Test AWS Connectivity

on:
  push:
    branches:
      - main

jobs:
  test-aws:
    runs-on: ubuntu-latest

    steps:
      - name: Debug Environment
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}
        run: |
          aws sts get-caller-identity || echo "Failed to authenticate"
